### ISSUE TITLE
It's not a real issue

### ISSUE THREAD

**Issue by ahmgeek** [mad-raz/rigeon#1]
well, I saw the release page, I saw this pattern:
```
on Dec 19, 2015 
v0.2.1  …
on Dec 19, 2015 
v0.2.0  …
Version 0.2.0
on Dec 19, 2015 
v0.1.2  …
on Dec 19, 2015 
```
almost three releases in one day :D ?

**Comment by mad-raz** [comment]
check the commit logs 
https://github.com/mad-raz/rigeon/commits/master

was nothing important but needed add a little modifications to the gem (and kept forgetting adding small things )
